sudo: required

language: python
arch:
    - arm64

python:
  - "3.8"

env:
  - ADMIN_PARTY=true COUCHDB_VERSION=2.3.1
  - ADMIN_PARTY=false COUCHDB_VERSION=2.3.1
  - ADMIN_PARTY=true COUCHDB_VERSION=1.7.2
  - ADMIN_PARTY=false COUCHDB_VERSION=1.7.2

services:
  - docker

before_install:
  - docker pull couchdb:$COUCHDB_VERSION
  - docker run -d -p 5984:5984 couchdb:$COUCHDB_VERSION

install: "pip install -r requirements.txt && pip install -r test-requirements.txt"

before_script:
    # Make sure CouchDB is up
    - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done
    - curl -X PUT http://localhost:5984/_users
    - curl -X PUT http://localhost:5984/_replicator

# command to run tests
script:
    - pylint ./src/cloudant
    - nosetests -A 'not db or ((db == "couch" or "couch" in db) and (not couchapi or couchapi <='${COUCHDB_VERSION:0:1}'))' -w ./tests/unit

notifications:
  email: false
